# Generated by Django 4.2.11 on 2026-03-18 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="next_step",
            field=models.ForeignKey(
                blank=True,
                help_text="Next step in linear flow (for simple workflows)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_steps",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="rejection_step",
            field=models.ForeignKey(
                blank=True,
                help_text="Step to go to when rejected (for approval steps)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_from_steps",
                to="workflows.workflowstep",
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="assigned_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("manager", "Manager"),
                    ("hr", "HR"),
                    ("ceo", "CEO"),
                    ("finance", "Finance"),
                ],
                max_length=50,
            ),
        ),
    ]
