# Generated by Django 4.2.11 on 2026-03-17 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("EXECUTE", "Executed"),
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                            ("SKIP", "Skipped"),
                            ("RETRY", "Retried"),
                            ("FAIL", "Failed"),
                            ("COMPLETE", "Completed"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("SIMULATE", "Simulated"),
                            ("PUBLISH", "Published"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_logs_content_b0ef47_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_logs_actor_i_5bd818_idx",
                    ),
                ],
            },
        ),
    ]
