# Generated by Django 4.2.11 on 2026-03-17 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_role", models.CharField(blank=True, max_length=50)),
                (
                    "approval_mode",
                    models.CharField(
                        choices=[
                            ("any_one", "Any One Approver"),
                            ("all", "All Approvers Required"),
                            ("majority", "Majority Required"),
                        ],
                        default="any_one",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("delegated", "Delegated"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("step_name", models.CharField(blank=True, max_length=255)),
                ("workflow_name", models.CharField(blank=True, max_length=255)),
                ("context_snapshot", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "approvals",
                "ordering": ["-created_at"],
            },
        ),
    ]
