# Generated by Django 4.2.11 on 2026-03-17 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("executions", "0001_initial"),
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="step_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="executions.stepexecution",
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="workflow_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="executions.workflowexecution",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["status", "assigned_to"], name="approvals_status_504d21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["workflow_execution", "status"],
                name="approvals_workflo_e3a09f_idx",
            ),
        ),
    ]
