# Generated by Django 4.2.11 on 2026-03-17 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("waiting", "Waiting for Approval"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("simulating", "Simulating"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic execution context. Populated from input + step outputs.",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("is_simulation", models.BooleanField(default=False)),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_executions",
                        to="workflows.workflowstep",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="workflows.workflowversion",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StepExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("waiting", "Waiting for Approval"),
                            ("retrying", "Retrying"),
                            ("timed_out", "Timed Out"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_context", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "applied_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_executions",
                        to="workflows.workflowrule",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="workflows.workflowstep",
                    ),
                ),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="executions.workflowexecution",
                    ),
                ),
            ],
            options={
                "db_table": "step_executions",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["status", "created_at"], name="workflow_ex_status_741304_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow_version", "status"],
                name="workflow_ex_workflo_e2d6ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["triggered_by", "created_at"],
                name="workflow_ex_trigger_ce05ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stepexecution",
            index=models.Index(
                fields=["workflow_execution", "status"],
                name="step_execut_workflo_476d40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stepexecution",
            index=models.Index(
                fields=["step", "status"], name="step_execut_step_id_751aec_idx"
            ),
        ),
    ]
