"""
Approval Model
"""
from django.db import models
from django.conf import settings
from apps.core.models import TimeStampedModel


class Approval(TimeStampedModel):
    """
    Represents an approval request generated by an approval-type step.
    Approval resolution triggers execution resumption via Celery.
    """

    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        APPROVED = 'approved', 'Approved'
        REJECTED = 'rejected', 'Rejected'
        DELEGATED = 'delegated', 'Delegated'
        EXPIRED = 'expired', 'Expired'

    class ApprovalMode(models.TextChoices):
        ANY_ONE = 'any_one', 'Any One Approver'
        ALL = 'all', 'All Approvers Required'
        MAJORITY = 'majority', 'Majority Required'

    step_execution = models.ForeignKey(
        'executions.StepExecution',
        on_delete=models.CASCADE,
        related_name='approvals',
    )
    workflow_execution = models.ForeignKey(
        'executions.WorkflowExecution',
        on_delete=models.CASCADE,
        related_name='approvals',
    )

    # Who needs to approve?
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='assigned_approvals',
    )
    assigned_role = models.CharField(max_length=50, blank=True)

    approval_mode = models.CharField(
        max_length=20,
        choices=ApprovalMode.choices,
        default=ApprovalMode.ANY_ONE,
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
        db_index=True,
    )

    # Resolution
    resolved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='resolved_approvals',
    )
    resolved_at = models.DateTimeField(null=True, blank=True)
    comments = models.TextField(blank=True)
    rejection_reason = models.TextField(blank=True)

    # Auto-expiry
    due_at = models.DateTimeField(null=True, blank=True)

    # Step metadata snapshot
    step_name = models.CharField(max_length=255, blank=True)
    workflow_name = models.CharField(max_length=255, blank=True)
    context_snapshot = models.JSONField(default=dict, blank=True)

    class Meta:
        db_table = 'approvals'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['status', 'assigned_to']),
            models.Index(fields=['workflow_execution', 'status']),
        ]

    def __str__(self):
        return f"Approval[{self.status}] for {self.step_name} → {self.assigned_to}"
